# Generated by Django 5.2.6 on 2025-09-08 17:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('5000000.00')), django.core.validators.MaxValueValidator(Decimal('50000000.00'))], verbose_name='Montant demandé (FCFA)')),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('document_projet', models.FileField(upload_to='documents/projets/', verbose_name='Document détaillant le projet')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('paye', 'Payé'), ('active', 'Actif')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('payment_key', models.CharField(blank=True, max_length=12, verbose_name='Clé de paiement')),
                ('montant_avance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name="Montant d'avance (15%)")),
                ('duree_remboursement_mois', models.IntegerField(default=84, verbose_name='Durée de remboursement (mois)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Demande de prêt',
                'verbose_name_plural': 'Demandes de prêts',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_key_entered', models.CharField(max_length=12, verbose_name='Clé de paiement saisie')),
                ('date_validation', models.DateTimeField(auto_now_add=True, verbose_name='Date de validation')),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_system.loanrequest', verbose_name='Demande de prêt')),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validated_payments', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('situation_matrimoniale', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, verbose_name='Situation matrimoniale')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Profession')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('piece_identite_recto', models.ImageField(blank=True, null=True, upload_to='documents/identite/', verbose_name="Pièce d'identité (recto)")),
                ('piece_identite_verso', models.ImageField(blank=True, null=True, upload_to='documents/identite/', verbose_name="Pièce d'identité (verso)")),
                ('justificatif_adresse', models.FileField(blank=True, null=True, upload_to='documents/justificatifs/', verbose_name="Justificatif d'adresse")),
                ('autre_document', models.FileField(blank=True, null=True, upload_to='documents/autres/', verbose_name='Autre document (optionnel)')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Compte validé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
